### ISSUE TITLE
Extended lcd_font_7x5 does not work

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Ultimaker2Marlin#102]
I want 0x80-0xff chars to display for future cyrillization. F.e. I added a string for 0x80 char to the end of lcd_font_7x5[]. But display shows garbage.  Chars 0x80 and higher are addressed out of lcd_font string.

**Comment by karabas** [comment]
The problem is that char is signed int. So I recommend to replace it to unsigned char:
 -   for( char c = pgm_read_byte(pstr); c; c = pgm_read_byte(++pstr))
 +  for(unsigned char c = pgm_read_byte(pstr); c; c = pgm_read_byte(++pstr))

**Comment by karabas** [comment]
Ok, no code changing required. Problem is solved adding Arduino IDE gcc flag -funsigned-char.

arduino\hardware\arduino\avr\platform.txt

compiler.cpp.flags=-c -g -Os {compiler.warning_flags} -std=gnu++11 -funsigned-char -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD

**Comment by karabas** [comment]
You may note it in docs if you want.

**Comment by Ghostkeeper** [comment]
Perhaps something for the build script?
