### ISSUE TITLE
#define SDcardDetect  -1 does not compile.

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Ultimaker2Marlin#103]
My sdcard reader is without sdcarddetect pin.
But if I config it as (by unknown reason I need to define in cardreader.h)
#define SDCARDDETECT  -1 
I got prerpocessor error compiling
So I ended up with
#define SDCARDDETECT  49
What is correct way to define?

**Comment by daid** [comment]
You do know this is the Ultimaker2 version of Marlin right? No effort has been made to make it work with different configurations.

**Comment by karabas** [comment]
Ok.
