### ISSUE TITLE
Endstop stuck detection bug

### ISSUE THREAD

**Issue by jorisa** [Ultimaker/Ultimaker2Marlin#111]
This seems like a bug in static void homeaxis(int axis).
Is it intentional that endstop stuck error can only be detected for z?

```
    if (endstop_pressed && axis == Z_AXIS)
    {
        SERIAL_ERROR_START;
        SERIAL_ERRORLNPGM("Endstop still pressed after backing off. Endstop stuck?");
        if (axis == Z_AXIS)
            Stop(STOP_REASON_Z_ENDSTOP_STUCK_ERROR);
        else
            Stop(STOP_REASON_XY_ENDSTOP_STUCK_ERROR);
        endstops_hit_on_purpose();
        return;
    }
```

**Comment by ckielstra** [comment]
Good find! This intentionally but should have been documented in the code, now the comment is only visible in the commit for this modified line.

Endstops can get stuck for all kinds of reasons and that's what the code tries to check. Problem is that we have field reports for wrong error messages happening. Until we know why these invalid messages were triggered, we disabled the error checking for the X- and Y-switches. The Z-axis is still being checked as we know material gets stuck in between the switch and this is a more severe error with potential physical damages.
