### ISSUE TITLE
imported material disappears after power off

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Ultimaker2Marlin#121]
When you export the materials list edit to add one then import it after a power cycle of the ultimaker 2+ it disappears from the list. the only way to have a custom material that stays in the list is to use the customise option.

**Comment by daid** [comment]
There is the bug that imports do not get "range checked" on import but only on startup. And if one of the values of any profile is out of range, everything resets to default.

**Comment by ChrisRiddell** [comment]
how do I know if a value is out of range? all I did was copy the CPE and changed the name and temps.

**Comment by ckielstra** [comment]
Several material import bugs have been fixed July 2018.
