### ISSUE TITLE
Reversing material: strange sequence

### ISSUE THREAD

**Issue by JPFrancoia** [Ultimaker/Ultimaker2Marlin#126]
Hi,

I recently flashed a new firmware to my UM2, because I added a titan E3D extruder. I modified the firmware a bit, but nothing exotic. I basically followed the steps in this tutorial:

https://wiki.e3d-online.com/wiki/E3D-v6_on_Ultimaker_2

Everything works perfectly (I can print), however duuring the reversing of material (when I want to change material), the extruder reverses a certain amount of filament fast (it lasts for ~3 seconds), then slows down (~3 seconds), then reverses fast again (~3 seconds), and so on. The sequence is repeated a few times.

It wasn't like that before I flashed the new firmware (but the firmware of my UM2 was never updated before, it's quite old). Before it was simply a long sequence of fast retraction.

Is it normal ? Did you change the reversing sequence at some point ?

**Comment by ckielstra** [comment]
We did not change (a lot) to the material change procedure.
On material removal the filament is first forwarded 20mm to try and remove a blob at the filament end,  then follows a single long retract of 76.5cm.

The behavior you describe sounds like a calculation with large values that's having an overflow. But could be anything else.
Did you have a look at this line in the E3D wiki?
#define DEFAULT_AXIS_STEPS_PER_UNIT   {80.0,80.0,200,837}  //837 to be changed to 418.5 for if a 200 steps/mm motor is used
Use one setting for the 200steps/mm motor and the other for a 400steps/mm motor. 

Did you try the firmware downloadable from the E3D wiki? How does that work?

I like to be of help, but:
We don't know which firmware repository you used as a basis.
We don't know what settings you changed.
We don't know your hardware.
You are applying changes not supported by Ultimaker.

For further help please visit the E3D forum or ask on the Ultimaker forum. Here on Github we only support the official Ultimaker software.
