### ISSUE TITLE
Clairify UltiLCD2 license

### ISSUE THREAD

**Issue by kallisti5** [Ultimaker/Ultimaker2Marlin#143]
The UltiLCD2 code was never upstreamed to Marlin.
I'd like to take a look at upstreaming the LCD code, however the license is unclear making it difficult.

Could Ultimaker clairify the license on these files?

* UltiLCD2*

A blanket "Ultimaker developed any changes or additions to Ultimaker2Marlin under the GPLv2" would be sufficient as well.

**Comment by kallisti5** [comment]
actually... nevermind!  Stock Marlin 2 works without needing the Ultimaker UltiLCD2 files.

**Comment by opserc20** [comment]
> actually... nevermind! Stock Marlin 2 works without needing the Ultimaker UltiLCD2 files.

Hi friend, can you help with the connections, i cant put the UM2 lcd to work on skr 1.3.
