### ISSUE TITLE
WiFi icon in the corner

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Ultimaker2Marlin#2]
. If it's connected it should show the signal strength.
- [ ] Designing of several icons: Wifi connection possible, AP mode, Connected Strong, Connected Medium, Connected Weak (signal), Wifi unavailable (crossed?)
- [ ] We should be able to display a Wifi pictogram in the corner of the screen
- [ ] The icon should be changed through status codes coming from the Linux-board

**Comment by ckielstra** [comment]
The UM2 has no WiFi and/or Linux board. This sounds like a request for a non-Ultimaker hardware setup or for the UM3 (see EM-1761).
