### ISSUE TITLE
Motor current left on after homing/levelling

### ISSUE THREAD

**Issue by andersolsson** [Ultimaker/Ultimaker2Marlin#31]
I noticed that the X-Y-motor stays powered indefinitely after leveling the buildplate and after running "Home Head".
I don't know if it is considered a bug or a feature but it seems unnecessary to keep them powered.

**Comment by ckielstra** [comment]
Dec 2016 the UM2* behavior was changed to be in line with the UM3. Motor power is now released after lowering the bed and after head homing. Raising the bed still keeps the motors powered to prevent the bed from sinking again.
