### ISSUE TITLE
still printing but cooling down if job was canceled

### ISSUE THREAD

**Issue by Killerregenwurm** [Ultimaker/Ultimaker2Marlin#38]
Hey guys,

I just recognize that Cura 14.07 (latest official Version and Firmware update) has some problems if the job was canceled.

I just pressed cancel for a job with very long edges. I know that the printing will stop if the printing Que of 20 "walks" is finished.
My problem is that during the "cancel is in progress" screen the nozzle is already cooling down and feeder is pushing also.
I used ABS and the temperature was very fast too low for printing but the Que wasn't empty and the feeder did not stop pushing.

I can think the best solution is to wait until the Que is empty before the nozzle is turned off. Or maybe it is also possible to stop the feeder if the job was canceled.

Greetings
Killerregenwurm

**Comment by ckielstra** [comment]
Jan 2015 the quickStop feature was added to the abort function which aborts all active moves and solves the issue mentioned here.
