### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by wolvesberry** [Ultimaker/Ultimaker2Marlin#39]
here's the error message:
" Wire\utility\twi.c.o: In function `__vector_39':
C:\Program Files (x86)\Arduino\libraries\Wire\utility/twi.c:364: multiple definition of`__vector_39'
UltiLCD2_low_lib.cpp.o:C:\Users\USERNAME\AppData\Local\Temp\build1949403233647085642.tmp/UltiLCD2_low_lib.cpp:181: first defined here
c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions "
How to solve it? Thanks.

**Comment by ckielstra** [comment]
The Readme.md document for this project here on github was updated for the required change to prevent the build error mentioned here.
