### ISSUE TITLE
Vanity mode

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Ultimaker2Marlin#4]
A mode for photography and demos, selectable in the advanced menu
- [ ] Allowing you to constantly see an Ultimaker logo with your own text, e.g. from display.txt (e.g. to display www.engadget.com under the logo).
- [ ] Allowing you to set the RGB colors of the rotation dial and the brightness of the backlight.

**Comment by ckielstra** [comment]
Funny feature request, but has been open for 5 years now. Closing it since has no priority anymore.
