### ISSUE TITLE
Write identifier file upon SD-card entry or upon start

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Ultimaker2Marlin#5]
Write identifier file upon SD-card entry or upon start

This can be used by Cura to trigger a question:
  "Would you like to switch to the Ultimaker Original profile?" 
    or 
  "Would you like to switch to the Ultimaker 2 profile?".

**Comment by ckielstra** [comment]
Cool idea, but never made it in the last 5 years and this status is not suspected to change.
