### ISSUE TITLE
15.01-RC8 Material change fails

### ISSUE THREAD

**Issue by melf1** [Ultimaker/Ultimaker2Marlin#59]
Hi,
I installed Cura 15.01-RC8 and uploaded the default firmware to an Ultimaker 2. Changing the filament doesn't work properly. The stepper motor that feeds the material goes bonkers:

Removal: https://www.youtube.com/watch?v=1_Ut64OuOzs
Insertion: https://www.youtube.com/watch?v=D8_MJxpzQIc

I switched back to the firmware that is shipped with cura 14.12.1 and the behaviour disappeared immediately.

**Comment by daid** [comment]
Yes, noticed the same on a few machines in the office. This is the result of me fixing another bug, causing the speed of the motor to be higher in the insertion/removal step. (it no longer "zigs/zags" now)

**Comment by melf1** [comment]
The commit e4f044e9244342cc8e51011114e414009b271e10 doesn't fix the problem on my machine. After a bit of trial and error I decreased both FILAMENT_INSERT_FAST_SPEED and FILAMENT_REVERSAL_SPEED to 130.
