### ISSUE TITLE
Wake-up light

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Ultimaker2Marlin#6]
Wake up with your Ultimaker, go to bed with your Ultimaker... Fade in lights at a certain time. 

Possible issues:
- Clock drift needs syncing?
- Clock needs sync
- Numeric Input

So this is why it's in the Icebox, but still the idea is cool.

**Comment by ckielstra** [comment]
Indeed a cool idea but closing since too many issues for realizing and has already been open for 5 years.
