### ISSUE TITLE
Extruder not work after aborting printing

### ISSUE THREAD

**Issue by GerogeFu** [Ultimaker/Ultimaker2Marlin#67]
Yesterday I try to change the material after aborting. but the extruder does not work after heating.Could anyone help me?

**Comment by daid** [comment]
Cannot seem to reproduce this issue. What steps did you do?
(Note, as a workaround, turning the machine on and off will reset and wrong internal state that might be causing this)

**Comment by ckielstra** [comment]
Closed since no response in 2 years.
When you think the issue was closed incorrectly, then please comment here and add the steps to reproduce the issue.
