### ISSUE TITLE
Wrong temperature for ABS: 280C - should be lower

### ISSUE THREAD

**Issue by DanielSjo** [Ultimaker/Ultimaker2Marlin#7]
In the Ultimaker 2 menu structure, you can select ABS as material. 
From MATERIAL->SETTINGS->ABS
The temperature is then set to 280C.

However, the firmware seems to have a limit (I'm guessing at 260C since that is the official highest in specifications in User Manual) whenever heating the printhead.

So when you do MATERIAL->CHANGE it first brings up:
"Heating printhead for material removal"
as it comes up in temperature (to 260C I guess)

it  eventually stops with an:
"ERROR - STOPPED Temp sensor contact support@ultimaker.com" 

I'm guessing this is simply about changing the ABS temperature to a lower value?

(It would of course be extremely useful to be able to add other materials and also change temperatures for both ABS and PLA)

**Comment by ckielstra** [comment]
Closing issue since it was fixed 2013-10-28.
