### ISSUE TITLE
Bug in material customization

### ISSUE THREAD

**Issue by FMMT666** [Ultimaker/Ultimaker2Marlin#9]
Material properties become messed up after custom entries are added.
Looks like the current changes are stored to a different, wrong place...
![mat1](https://f.cloud.github.com/assets/3057791/1557313/f4af597e-4f0e-11e3-9a91-80ee87bfecab.jpg)
![mat2](https://f.cloud.github.com/assets/3057791/1557312/f4ad34b4-4f0e-11e3-9a79-07785478459f.jpg)

**Comment by ckielstra** [comment]
Lots of fixes and changes were made to the material handling since this bug was reported. The problem hasn't been reported recently so I close this ticket.
