### ISSUE TITLE
Material name restricted to 8 Characters

### ISSUE THREAD

**Issue by jstrobel** [Ultimaker/Ultimaker2Marlin#90]
When i use custom Materials the Name is restricted to 8 Characters and will be cut off.
e.g. Ninja Flex become Ninja Fl
As seen on other entries in the list like "Import from SD" there is space to show more characters.

**Comment by jstrobel** [comment]
Firmware: 15.04.3

**Comment by daid** [comment]
This is by design, to save memory space. Writable memory is really tight in the firmware.

**Comment by jstrobel** [comment]
Thanks for the info.
